Tiich/Controllers/WorkshopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TiichDAL;
using TiichService.Service;
using Utils;

namespace Tiich.Controllers
{
    public class WorkshopController : Controller
    {
        [HttpGet]
        public ActionResult Create(int id = -1)
        {
            Workshop ws = new Workshop();
            WorkshopService service = new WorkshopService();
            UserService userService = new UserService();

            if(id != -1)
            {
                ws = service.Find(id);
            }

            if(User.Identity.IsAuthenticated)
            {
                TempData["UserID"] = userService.GetUserByName(User.Identity.Name).ID;
            }
            
            if(id != -1 && User.Identity.IsAuthenticated)
            {
                service.AddVisitorToWorkshop(TempData["UserID"].ToString(), id);
                //int userID = int.Parse(TempData["UserID"]);
                //if(userID != )
            }
        
            return View(ws);
        }

        [HttpPost]
        public ActionResult Create(Workshop ws)
        {
            UserService userService = new UserService();
            WorkshopService service = new WorkshopService();
            ErrorHandler eh = new ErrorHandler();
            User user = userService.GetUserByName(User.Identity.Name);

            if(ws.ID == 0)
            {
                //Consolidation
                ws.User = user;
                ws.CreationDate = DateTime.Now;

                service.Add(ws, eh, new List<object>() { user });

            }
            else
            {
                ws.UserID = user.ID;
                service.Edit(ws, eh);
            }

            if (User.Identity.IsAuthenticated)
                TempData["UserID"] = userService.GetUserByName(User.Identity.Name).ID; 
            
            //return View(ws);
            return RedirectToAction("Index", "Home");

        }

        public ActionResult Participate()
        {
            int userID = int.Parse(Request["userID"]);
            int wsID = int.Parse(Request["workshopID"]);

            WorkshopService service = new WorkshopService();
            service.AddParticipant(userID, wsID);

            return RedirectToAction("Create", new { @id = wsID });
        }

        public ActionResult UnParticipate()
        {
            int userID = int.Parse(Request["userID"]);
            int wsID = int.Parse(Request["workshopID"]);

            WorkshopService service = new WorkshopService();
            service.RemoveParticipant(userID, wsID);

            return RedirectToAction("Create", new { @id = wsID });
        }
        
    }
}

Tiich/Views/Workshop/Create.cshtml
@model TiichDAL.Workshop

@{
    ViewBag.Title = "Proposer";
    string x = null;
    if(TempData["UserID"] != null)
    {
        x = TempData["UserID"].ToString();
    }

    bool edit = false;
    
    if(Model.ID == 0)
    {
        edit = true;
    }
    else if(Model.UserID.ToString().Equals(x))
    {
        edit = true;
    }
    
    if(!edit && x != null)
    {
        TiichService.Service.WorkshopService service = new TiichService.Service.WorkshopService();
        service.AddVisitorToWorkshop(TempData["UserID"].ToString(), Model.ID);
    }
}
<div class="container-padded">
    @using (Html.BeginForm("Create", "Workshop", FormMethod.Post))
    {
        if (edit)
        {
            @Html.HiddenFor(m => m.CreationDate)
            @Html.HiddenFor(m => m.User)
            @Html.HiddenFor(m => m.UserID)
            @Html.HiddenFor(m => m.Lat)
            @Html.HiddenFor(m => m.Lng)
    <input type="hidden" value="@Model.Lat" id="oldLat" />
    <input type="hidden" value="@Model.Lng" id="oldLng" />

        }
        else
        {
        }
        <div class="col-lg-10 col-lg-offset-1">
            <div class="panel panel-group panel-custom">
                <!-- Heading -->
                <div class="panel-heading ">
                    <h1>
                        @{
                        if (edit)
                        {
                            @Html.TextBox("Label", Model.Label, new { @class = "form-control", @placeholder = "Votre titre ici" })
                        }
                        else
                        {
                            @Model.Label
                        }
                                        }
                    </h1>
                </div>

                <!-- Content-->
                <div class="panel-body">
                    <div class="col-lg-8">
                        <div class="well col-lg-12" style="height:100%;">
                            <div class="col-lg-6">
                                <div>
                                    @if (edit)
                                    {
                                        <p class="list-group-item">Date : @Html.TextBoxFor(model => model.Date, new { type = "date", @class = "form-control", @value = DateTime.Now.ToShortDateString() })</p>
                                        <p class="list-group-item">Heure : @Html.TextBoxFor(i => i.Hour, new { type = "time", @class = "form-control", @placeholder = DateTime.Now.AddHours(1).ToShortTimeString() })</p>
                                    }
                                    else
                                    {
                                        <p class="list-group-item">Date : @DateTime.Now.ToShortDateString()</p>
                                        <p class="list-group-item">Heure : @DateTime.Now.AddHours(1).ToShortTimeString()</p>
                                    }
                                </div>
                            </div>
                            <div class="col-lg-6">
                                @if (edit)
                                {
                                    @Html.TextBox("address", Model.Address, new { @placeholder = "Nowhere"})
                                }
                                else
                                {
                                    @Html.TextBox("address", Model.Address, new { @placeholder = @Model.Address, @class = "disabled" })
                                }

                                <div id="map">
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-5 well">
                            <h3>Détails</h3>
                            <p>
                                @if (edit)
                                {
                                    @Html.TextArea("details", Model.Details, new { @class = "form-control" })
                                }
                                else
                                {
                                    @Model.Details
                                }
                            </p>
                        </div>

                        <div class="col-lg-6 col-lg-offset-1 well">
                            <h3>A prévoir</h3>
                            <p>
                                @if (edit)
                                {
                                    @Html.TextArea("equipement", Model.Equipement, new { @class = "form-control" })
                                }
                                else
                                {
                                    @Model.Equipement
                                }
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-4" style="height:100%;">
                        <div class="well col-lg-12">
                            @if (edit)
                            {
                                <h4>Participants :</h4>
                                <div class="form form-inline">
                                        <p class="">Minimium :</p>
                                        @Html.TextBoxFor(i => i.PeopleMin, new { @type = "number", @class = "form-control " })
                                </div>
                                <div class="form-group">
                                    <p>Maximum :</p>
                                    @Html.TextBoxFor(i => i.PeopleMax, new { @type = "number", @class = "form-control col-lg-6" })
                                </div>
                                <br/>
                                <div class="form-group col-lg-12" style="margin-top:20px;">
                                    <input type="submit" class="btn btn-primary " />
                                </div>
                            }
                            else
                            {
                                <div style="display:inline-block;margin-bottom:15px;" class="col-lg-12">
                                    @{
                                int participants = 0;
                                foreach (TiichDAL.User us in Model.Participants)
                                {
                                    string imgPath = "/Content/Avatars/" + (us.Avatar == null ? "null.png" : us.Avatar);
                                    <img src=@imgPath class="roundedImage col-lg-2" style="margin:0;padding:0;" />
                                    participants++;
                                }

                                for (int i = participants; i < Model.PeopleMax; i++)
                                {
                                    <img src="~/Content/Avatars/emptySpace.png" class="roundedImage roundedImage-mini " style="display:inline;margin-top:0px;" />
                                }

                                if (User.Identity.IsAuthenticated)
                                {
                                    <div class="col-lg-12" style="margin-top:15px;">
                                        @{
                                    TiichDAL.User us = new TiichService.Service.UserService().GetUserByName(User.Identity.Name);
                                        }
                                        @if (Model.Participants.Where(u => u.ID == us.ID).FirstOrDefault() != null)
                                        {
                                            @Html.ActionLink("Se désinscire", "UnParticipate", new { userID = TempData["UserID"], workshopID = Model.ID }, new { @class = "btn btn-danger" })
                                        }
                                        else
                                        {

                                            if (participants == Model.PeopleMax)
                                            {
                                                <div class="col-lg-8 btn btn-danger col-lg-offset-2">
                                                    <h4>Atelier complet</h4>
                                                </div>
                                            }
                                            else
                                            {
                                                @Html.ActionLink("Participer", "Participate", new { userID = TempData["UserID"], workshopID = Model.ID }, new { @class = "btn btn-success" })
                                            }
                                        }
                                    </div>
                                }
                                    }
                                </div>
                            }
                        </div>

                        @if (!edit)
                        {
                            <div class="well col-lg-12" style="height:100%;">
                                @{
                            string imgPath = "/Content/Avatars/" + (Model.User.Avatar == null ? "null" : Model.User.Avatar) + ".png";
                            <img src=@imgPath class="roundedImage" />
                                    <h3>@Model.User.FirstName</h3>
                                    <h3>@Model.User.LastName</h3>
                                }

                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
<script src="~/Scripts/Gmap.js"></script>
<script type="text/javascript">

    function updateSlideValue(newValue) {
        alert(newValue);
        document.getElementById("range").innerHTML = newValue;
    }
    $(document).ready(function () {
        $("#address").addClass("form-control");
        $("#address").keypress(function (event) {
            if (event.which == 13) {
                event.preventDefault();
            }
        })
    });
</script>

Tiich/Views/Workshop/Index.cshtml
@{
    ViewBag.Title = "Proposer";
}



<div class="col-lg-10 col-lg-offset-1">
    <div class="well">
        <h1>Titre</h1>

    </div>


    <div class="col-lg-7 well">
        <p>Contenu</p>
    </div>
    <div class="col-lg-4 col-lg-offset-1 jumbotron" style="height:100%;padding:2px;">
        <div id="map"></div>
    </div>

    <div class="col-lg-12 well">
        <p>Participants</p>
    </div>
</div>


<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAN8_vIEFzgTRdFmsvTMovR9IS7ufIxWoA">
</script>
<script type="text/javascript">
    function initialize() {

        var x = 50;
        var y = 50;
        var map;
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(
                function (pos) {

                    //center
                    x = pos.coords.latitude;
                    y = pos.coords.longitude;
                    var me = new google.maps.LatLng(pos.coords.latitude, pos.coords.longitude);
                    mapOptions = {
                        center: { lat: x, lng: y },
                        zoom: 17
                    };
                    var map = new google.maps.Map(document.getElementById('map'), mapOptions);

                    //Place
                    var marker = new google.maps.Marker({
                        position: new google.maps.LatLng( x,y),
                        map: map,
                        title: 'Vous êtes ici'
                    });

                }
                );
        }
        else {
            alert("Pas de géoloc");
        }
        
    }
    google.maps.event.addDomListener(window, 'load', initialize);


</script>

Tiich/Views/Workshop/Miniature.cshtml
@model List<Tiich.ViewModels.VMWorkshop>

@{
    int index = 0;
    int totalWs = 0; ;
    foreach(var vm in Model)
    {
        if(vm.Workshops != null)
        {
            if(vm.Workshops.Count != 0)
            {
                <div class="panel panel-group panel-custom">
                    <div class="panel-heading "  role="tab" >
                        <h3 style="display:inline-block;">
                                @vm.Category
                        </h3>
                        <ul style="display:inline-block;float:right;height:100%;background-color:white;font-size:1.5em;" class="nav nav-pills">
                            <li class="navbar-brand" onclick="SortBy(@(index),'distance')">
                                <span class=" glyphicon glyphicon-plane" style="font-size:1.1em;"> </span>
                            </li>
                            <li class="navbar-brand" onclick="SortBy(@(index),'date')">
                                <span class=" glyphicon glyphicon-calendar" style="font-size:1.1em;"></span>
                            </li>
                            <li class="navbar-text wraper" id="@index" style="background-color: #3498db;">
                                <span class="btn" style="color:white;">@vm.Workshops.Count</span>
                            </li>
                        </ul>
                    </div>
                     <ul class="list-group" id=@("content" + index)>
                            @{
                            int i = 0;
                            foreach (var ws in vm.Workshops)
                            {
                                string style = i % 2 == 1 ? "background-color:#EEEEEE;" : "";
                        <li class="panel-body list-group-item clickableList" style="@style" id="@ws.ID">
                            <input type="hidden" id="indexOnTotal@(ws.ID)" value="@totalWs"><!-- Workshop -->
                            <div class="col-lg-9">
                                <h3>@ws.Label.Trim()</h3>
                                <p>@ws.Details</p>
                                <p>@ws.Address</p>
                                <p id="wsDate_@(ws.ID)">@ws.CreationDate</p>

                                <h4 id="wsKm_@totalWs" class="km">

                                </h4>
                                <input type="hidden" id="wsLat_@totalWs" value="@ws.Lat"/>
                                <input type="hidden" id="wsLng_@totalWs" value="@ws.Lng"/>
                            </div>

                            <!-- User-->
                            <div class="col-lg-3">

                                <a href="User/Account/@ws.UserID">
                                    @{

                                string imgPath = "/Content/Avatars/" + (ws.User.Avatar == null ? "null" : ws.User.Avatar) + ".png";
                                            <img src=@imgPath class="roundedImage" />
                                    }
                                </a>

                            </div>
                        </li>
                                i++;
                                totalWs++;
                            }
                            }
                        </ul>
                </div>
            }
        }
    index++;
    <input type="hidden" id="totalWS" value="@totalWs" />
}

}

<!-- sorting scripts -->
<script type="text/javascript">

    function ExtractWorkshopsIDS(id)
    {
        var cId = "content" + id;
        var ws = $("#" + cId).find("li");

        var res = [];
        for (var i = 0; i < ws.length; i++) {
           
            var id = ws[i].id;
            //alert(id);
            res.push(id);
        }
        return res;
    }


    function SortBy(contentID, sortType)
    {
        var wsTab = [];
        var wsTab = ExtractWorkshopsIDS(contentID);
        var assoArray = [];

        switch (sortType) {
            case "distance":
                //Fill Array
                for (var i = 0; i < wsTab.length; i++) {
                    var id = wsTab[i];
                    var val = $("#indexOnTotal" + id).val();

                    var kmID = "#wsKm_" + val;
                    var kmDiv = $(kmID).html();
                    var kmValue = -1;

                    //alert(kmID);
                    kmValue = parseFloat(kmDiv.replace("km", ""));

                    if (isNaN(kmValue)) {
                        kmValue = -1;
                    }
                    assoArray.push({ name: id, value: kmValue });
                }

                //sort array
                assoArray = assoArray.sort(function (a, b) {
                    return a.value < b.value;
                });

                break;
            case "date":
                //Fill Array
                for (var i = 0; i < wsTab.length; i++) {
                    var id = wsTab[i];
                    var val = $("#indexOnTotal" + id).val();
                    var dateID = "#wsDate_" + id;
                    var dateVal = $(dateID).html();
                    assoArray.push({ name: id, value: dateVal });

                    assoArray = assoArray.sort(function (a, b) {
                        var da = a.value.split(" ")[0].split("/");
                        var dateA = new Date(da[2],da[1], da[0]);
                        
                        var db = b.value.split(" ")[0].split("/");
                        var dateB = new Date(db[2],db[1], db[0]);

                        return dateA.getTime() < dateB.getTime();
                    });
                }
                break;
            default:

        }
        
        alert(JSON.stringify(assoArray));
        var replacingHtml = "";
        for (var i = 0; i < assoArray.length; i++) {
            var id = assoArray[i].name;

            var text = $("#" + id).html();

            // rebuilding 
            var style = i % 2 == 1 ? "background-color:#EEEEEE;" : "";
            text = "<li class='panel-body list-group-item clickableList' style='" + style + "' id="+ id + ">" + text;
            text += "</li>";
            ///

            replacingHtml += text;
        }
        //alert(replacingHtml);

        //alert($("#content" + contentID).html());
        $("#content" + contentID).html(replacingHtml);
        $(".clickableList").click(function (obj) {
            var id = $(this).attr('id');
            window.location.replace("/Workshop/Create/" + id);
        })
    }
</script>   
 
<script type="text/javascript">
    $(document).ready(function () {
        $(".clickableList").click(function (obj) {
            var id = $(this).attr('id');
            window.location.replace("/Workshop/Create/" + id);
        })

        $(".wraper").click(function (obj) {
          
            var id = $(this).attr('id');
            $("#content" + id).slideToggle(1000);
        })
    })

    function distance(lat1, lon1, lat2, lon2, unit) {
        //alert(lat1 + " " + lat2 + "// " + )
        var radlat1 = Math.PI * lat1 / 180
        var radlat2 = Math.PI * lat2 / 180
        var radlon1 = Math.PI * lon1 / 180
        var radlon2 = Math.PI * lon2 / 180
        var theta = lon1 - lon2
        var radtheta = Math.PI * theta / 180
        var dist = Math.sin(radlat1) * Math.sin(radlat2) + Math.cos(radlat1) * Math.cos(radlat2) * Math.cos(radtheta);
        dist = Math.acos(dist)
        dist = dist * 180 / Math.PI
        dist = dist * 60 * 1.1515
        if (unit == "K") { dist = dist * 1.609344 }
        if (unit == "N") { dist = dist * 0.8684 }
        return dist
    }


    function showMap(position) {
        // Show a map centered at (position.coords.latitude, position.coords.longitude).

        var myLat = position.coords.latitude;
        var myLng = position.coords.longitude;

        var latsuff = "wsLat_";
        var lngsuff = "wsLng_";
        var kmsuff = "wsKm_";
        var i = 0;
        var nbWs = parseInt($("#totalWS").val());

        for (var i = 0; i <= nbWs ; i++) {
            var lt = "#" + latsuff + i;
            var lg = "#" + lngsuff + i;
            var kms = "#" + kmsuff + i;
            var localLat = $(lt).val();
            var localLng = $(lg).val();

            if (localLat != null)
            {
                localLat = localLat.replace(",", ".");
                localLng = localLng.replace(",", ".");
                localLat = parseFloat(localLat);
                localLng = parseFloat(localLng);


                var km = distance(myLat, myLng, localLat, localLng, "K");

                if (!isNaN(km)) {
                    km = Math.round(km, 2);
                    var processedKm = km + " km";
                    //processedKm = (myLat + " " + localLat + " " + myLng + " " + localLng);
                    $(kms).html(processedKm);
                }
            }
        }

    }
    // One-shot position request.
    navigator.geolocation.getCurrentPosition(showMap);
</script>