Tiich/Controllers/ModerationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Tiich.ViewModels;
using TiichDAL;
using TiichService.Service;

namespace Tiich.Controllers
{
    public class ModerationController : Controller
    {
        //
        // GET: /Moderation/
        [HttpGet]
        public ActionResult Index(List<int> ws = null)
        {
            return View(ws);
        }

        public ActionResult PartialAjaxTest(string text)
        {
            return View("PartialAjaxTest", text);
        }

        public ActionResult GlobalTagsStatistics()
        {
            VMTagsStatistics vm = new VMTagsStatistics();

            //Get tags
            TagService tagService = new TagService();
            List<Tag> tags = tagService.GetMostUsed(7);
            
            //Consolidate VM
            vm.CreateTagList(tags);

            return View(vm);
        }

        public ActionResult TopAndFlopWorkshops()
        {
            WorkshopService service = new WorkshopService();
            List<Workshop> workshops = new List<Workshop>();

            workshops.AddRange(service.GetTopViewed(5).ToList());
            workshops.AddRange(service.GetFlopViewed(5).ToList());

            return View(workshops);
        }

        public ActionResult GetCommonWords(string tag)
        {
            TagService service = new TagService();

            List<Tag>[] words = service.GetCommonWords(tag);

            VMTagManager vm = new VMTagManager()
            {
                DirectTags = words[0],
                IndirectTags = words[1]
            };

            return View(vm);
        }

        [HttpPost]
        public ActionResult Index()
        {
            string direct = "direct";
            string indirect = "indirect";
            List<int> directIDS = new List<int>();
            List<int> indirectIDS = new List<int>();

            int i = 0;

            while(Request.Params[direct + i] != null)
            {
                directIDS.Add(int.Parse(Request.Params[direct + i]));
                i++;
            }

            i = 0;
            while (Request.Params[indirect + i] != null)
            {
                indirectIDS.Add(int.Parse(Request.Params[indirect + i]));
                i++;
            }

            bool activate = bool.Parse(Request.Params["activate"]);

            List<int> tags = new List<int>();
            tags.AddRange(directIDS);
            tags.AddRange(indirectIDS);

            TagService service = new TagService();
            service.SetTags(directIDS, activate);
            List<Workshop> works = service.GetWorkshopsFromTags(directIDS);
            WorkshopService wService = new WorkshopService();

            int wCount = works.Count;

            List<int> ids = new List<int>();
            works.ForEach(w => ids.Add(w.ID));

            //works.ForEach(w => wService.AutoTag(w));
            //works.ForEach(w => wService.Update(w, w.Tag.ToList()));


            return Index(ids);
        }
    
        public void UpdateWorkshop(int id)
        {
            WorkshopService service = new WorkshopService();

            using (TiichEntities context = new TiichEntities())
            {
                Workshop w = context.Workshop.Include("Tag").First(ws => ws.ID == id);

               service.AutoTag(w);
               service.Update(w, w.Tag.ToList());
            }
        }

        public void ReviewAll()
        {
            WorkshopService service = new WorkshopService();

            using(TiichEntities context = new TiichEntities())
            {
                List<Workshop> ws = context.Workshop.Include("Tag").ToList();

                ws.ForEach(w => service.AutoTag(w));
                ws.ForEach(w => service.Update(w, w.Tag.ToList()));
            }
        }
    }
}

Tiich/Views/Moderation/GetCommonWords.cshtml
@model Tiich.ViewModels.VMTagManager

@using (Html.BeginForm("Index", "Moderation", FormMethod.Post, new {@id="form" }))
{
    int i = 0;
    foreach (TiichDAL.Tag tag in Model.DirectTags)
    {
        <input name="@("direct" + i)" type="hidden" value="@tag.ID"/>
        <label class="form-control">
            @{
        string ch = tag.activate == 1 ? "true" : "false";
        string cheked = tag.activate == 1 ? "checked" : "";

                <input type="checkbox" class="clickableCheckbox" @cheked title="@tag.label" value="@tag.label.Trim()" />
                <input type="hidden" name="activate" id="activate" value="@ch"/>
        i++;
}
            @tag.label.Trim()
        </label>

    }
    i = 0;
    foreach (TiichDAL.Tag tag in Model.IndirectTags)
    {
        <input type="hidden" name="@("indirect" + i)"  value="@tag.ID" />
        i++;
    }
    <input type="submit" value="Enregistrer" id="recordChanges" class="btn btn-primary" data-toggle="modal" data-target="#myModal" />
}


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <img src="~/Content/Images/loader.gif" height="300" width="300"/>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#recordChanges").click(function () {
            $("#form").submit();
        })

        $("#closeError").click(function () {
            $("#SuccesModal").remove();
        })

        $(".clickableCheckbox").click(function (evt) {
            var box = $(this);
            $("#activate").val(box.prop("checked"));
            //alert(box.prop("checked"));
            /*$.ajax({
                url: "UpdateActivatedTag?tag=" + $(this).val() + "&activate=" + box.prop("checked"),
            })
             .done(function (data) {
                 location.reload();
             });*/
        })

    });

</script>

Tiich/Views/Moderation/GlobalTagsStatistics.cshtml
@model Tiich.ViewModels.VMTagsStatistics

<style type="text/css">
    div.legend-span {
        width: 20px;
        height: 20px;
        border-radius: 50px;
        font-size: 20px;
        color: #fff;
        line-height: 100px;
        text-align: center;
        display: inline-block;
        background: #000;
    }

    div.legend-text{
        display:inline-block;
        padding:5px;
        margin:auto;
        height:100%;
    }

    ul{
        list-style:none;
    }
</style>
<div id="chartValues">
    @{
        int i = 0;       
        foreach (var tagCount in Model.Tags)
        {
            string keyIndex = "chart_key" + i;
            string valueIndex = "chart_val" + i;
    
            <input id="@keyIndex" type="hidden" value="@tagCount.Tag.label.Trim()"/>
            <input id="@valueIndex" type="hidden" value="@tagCount.Count"/>
            i++;
        } 
        <input id="chart_lastindex" value="@i" type="hidden"/>
    }
    

</div>

<h1>Global stats</h1>

<script src="~/Scripts/Chart/Chart.min.js"></script>
<script src="~/Scripts/Chart/ColorList.js"></script>
<!-- pie chart tests -->
<div id="canvas-holder">

    <canvas id="chart-area" width="500" height="300" class="col-lg-8"/>
    <div class="col-lg-4">
        <ul id="chart-legend">

        </ul>
    </div>


    <div class="col-lg-12" id="commonWords">

    </div>
</div>

<script>


    var nbTags = $("#chart_lastindex").val();
    var data = [];
    for (var i = 0; i < nbTags; i++) {
        var key = ($("#chart_key" + i).val());
        var val = (parseInt($("#chart_val" + i).val()));
        var row = {
            value: val,
            color: COLOURS[i % (COLOURS.length)].color,
            highlight: COLOURS[i % (COLOURS.length)].highlight,
            label: key,
            labelColor: 'white',
            labelFontSize: '16'
        };
        //data.push(row)

        data.push(row);
    }

    var options = [{
        animationEasing: "easeOutBounce",
        legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<segments.length; i++){%><li><span style=\"background-color:<%=segments[i].fillColor%>\"></span><%if(segments[i].label){%><%=segments[i].label%><%}%></li><%}%></ul>"

    }];
    var ctx = document.getElementById("chart-area").getContext("2d");
    window.myPie = new Chart(ctx).Pie(data, options);
    //window.myPie.generateLegend();
   
    $("#chart-area").click(
    function (evt) {
        var activePoints = window.myPie.getSegmentsAtEvent(evt);
        var tag = activePoints[0].label;
        $.ajax({
            url: "/Moderation/GetCommonWords?tag=" + tag,
        })
             .done(function (data) {
                 $("#commonWords").html(data);
             });
        /* do something */
    }
);

    for (var i = 0; i < data.length; i++) {
        var row = "<li class='legend'><div class='legend-span' style=\"background-color:" + data[i].color + "\"></div><div class='legend-text'>" + data[i].label + "</div></li>";
        $("#chart-legend").append(row);
    }
</script>

Tiich/Views/Moderation/Index.cshtml
@model List<int>

<div class="container-padded">

    <!-- Pie chart div -->
    <div id="pieChartDiv" class="col-lg-7 well">
        <div id="tagsStatistics">
            <img src="~/Content/Images/loader.gif" />
        </div>
        <div>
            @Html.ActionLink("Tout appliquer", "ReviewAll",null, new {@class = "btn btn-primary btn-lg"});
        </div>
    </div>

    <!-- Right col-->
    <div class="col-lg-5">
        
        <!-- most viewed-->
        <div id="topAndFlopWorkshops" class="well col-lg-12">
            <img src="~/Content/Images/loader.gif" />
        </div>

        <!-- Workshop -->
        <div>

        </div>
    </div>

</div>

<div>
    @if(Model != null)
    {
        int count = 1;
        <input type="hidden" id="wCount" value="@Model.Count" />
        foreach(int i in Model)
        {
            <input type="hidden" id="@("w"+ count)" value="@i" />
            count++;
        }
        
        <div class="modal fade in visible-lg  " id="progModal">
            <div class="modal-dialog ">
                <div class="modal-content ">
                    <div class="modal-body" id="progressStatus">
                        <div class="progress">
                            <div class="progress-bar" id="progressBar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="0" style="width:0%;">
                                0%
                            </div>
                        </div>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
    }
</div>
<script type="text/javascript">
    $(document).ready(function () {
        var count = $("#wCount").val();
        var ajaxFunc = function (i) {
            var id = parseInt($("#w" + i).val());
            $.ajax({
                url: "/Moderation/UpdateWorkshop?id=" + id,
            })
                            .complete(function () {
                                if(isNaN(id))
                                {
                                    $("#progModal").remove();
                                    //Call global stats
                                    $.ajax({
                                        url: "/Moderation/GlobalTagsStatistics",
                                    })
                                         .done(function (data) {
                                             $("#tagsStatistics").html(data);
                                         });

                                    //Call most and less viewed worksops
                                    $.ajax({
                                        url: "/Moderation/TopAndFlopWorkshops",
                                    })
                                         .done(function (data) {
                                             $("#topAndFlopWorkshops").html(data);
                                         });

                                }
                                else {
                                    $("#currentProcess").html(i);
                                    $("#progressBar").attr("aria-valuenow", i);
                                    var percent = i / parseInt(count)* 100;
                                    $("#progressBar").html(percent + "%");
                                    $('#progressBar').css('width', percent + '%').attr('aria-valuenow', i);
                                    i = i + 1;
                                    ajaxFunc(i);
                                }
                            })
                         .done(function (data) {
                         });
        }
        if (count != null)
        {
            count = parseInt(count);
            $("#progressBar").attr("aria-valuemax", count);
            $("#totalProcess").html(count);
            ajaxFunc(1);
        }
        else
        {
            //Call global stats
            $.ajax({
                url: "/Moderation/GlobalTagsStatistics",
            })
                 .done(function (data) {
                     $("#tagsStatistics").html(data);
                 });

            //Call most and less viewed worksops
            $.ajax({
                url: "/Moderation/TopAndFlopWorkshops",
            })
                 .done(function (data) {
                     $("#topAndFlopWorkshops").html(data);
                 });

        }
  });
    //$("#ajax").load("/Moderation/PartialAjaxTest/?text=tets");
</script>

Tiich/Views/Moderation/PartialAjaxTest.cshtml
@model string

<h1>@Model</h1>

Tiich/Views/Moderation/TopAndFlopWorkshops.cshtml
@model List<TiichDAL.Workshop>

<div class="col-lg-6">
    <h1>Top 5</h1>
    <ul class="list-group">
        @for (int i = 0; i < 5; i++)
        {
            <li class="list-group-item">
                @Model.ElementAt(i).Label
            </li>
        }
    </ul>

</div>
<div class="col-lg-6">
    <h1>Flop 5</h1>
    <ul class="list-group">
        @for (int i = 9; i >= 5; i--)
        {
            <li class="list-group-item">
                @Model.ElementAt(i).Label
            </li>
        }
    </ul>
</div>